char *ListaArmas[434] = {
"M9", 
"Colt 1911A1 MEU", 
"Mossberg 590 Military", 
"MP5A4", 
"M4A1", 
"MK.48", 
"M24", 
"M67", 
"XM84", 
"M18 Smoke", 
"HK USP", 
"MP5 SD", 
"AK-47", 
"M4Devgru", 
"SA-18",//15
        //16 null
"XK-2", //17
"RMS12", 
"M-23F", 
"G7A", 
"M16A3", 
"K1A", 
"Knight's SR25", 
"Benelli M4 Super 90", 
"Beretta M92FS", 
"G36E", 
"FN Minimi", 
"L96A1", 
"M16A1 Mine", 
"LAW", //30
       //31 null 
"Heartbeat sensor", //32 
"LGB SHELL", 
"MK16 SCAR-L", 
"IMI UZI", 
"M60", 
"SPAS-12", 
"Remington 870", 
"Glock 23", 
"AUG-A1", 
"UMP", 
"AKS-74U", 
"MSG-90", 
"K2", 
"K3", 
"K7", 
"K5", 
"Beretta M92F SE", 
"Glock 23 SE", 
"SCAR-L Black", 
"M24 CAMO", 
"USP Tactical", 
"M590 CQB", 
"M4A1 CQBR", 
"L96A1 Ghillie", 
"MP5RAS", 
"AK-103", 
"SPAS12 Stock", 
"M11-Tactical Knife", 
"Ninjato", 
"Machete", 
"P226", 
"AK-47 npc", 
"IMI UZI npc", 
"M24 npc", 
"M60 npc", 
"LAW npc", 
"M16A3"/*"Mini-Gun npc"*/, 
"M67 npc", 
"Dynamite npc", 
"SR25 Sandfire", 
"K3 SPW", 
"Springfield M14", 
"Ingram M10", 
"Colt Anaconda Black", 
"Colt Anaconda Silver", 
"GI Shovel", 
"M4A1 Desert Aim", 
"M1911 Knights", 
"FAMAS", 
"P90", 
"AK-47 Gold", 
"MP5 RAS Centurion", 
"Sickle", 
"M69HE", 
"M60 Steel", 
"M136 AT4 Bounty", 
"RMS12 Bounty", 
"Double Barrel", 
"Double Barrel Punisher", 
"P226 Silver", 
"G18", 
"Kukuri", 
"HeartBeat Detector", 
"Mini-Gun Bounty", 
"Dragunov SVD", 
"Dragunov Black", 
"L96A1 ArcticWolf", 
"G36E Valkyrie", 
"SCAR-L Trispear", 
"Snow Ball", 
"Ice Ball", 
"Snow Shovel", 
"Snow Grenade", 
"SIG550", 
"SAIGA 20K", 
"P90TR", 
"Bowie Knife", 
"M416", 
"M416 CQB", 
"DesertEagle", 
"DesertEagle SE", 
"Strider Axe", 
"M69HE NL", 
"G36KE", 
"G36C", 
"SCAR H", 
"L96A1 Super Magnum", 
"Anaconda Silver 8inch", 
"M590 SE", 
"M590 CQB SE", 
"Anaconda Black 8inch", 
"Mossberg 590 Military P", 
"Benelli M4 Super 90 P", 
"SPAS-12 P", 
"Remington 870 P", 
"M590 CQB P", 
"SPAS12 Stock P", 
"SAIGA 20K P", 
"Double Barrel P", 
"Double Barrel Punisher P", 
"AK-103 GoldPlanted", 
"M4A1SOPMOD", 
"P90 SE", 
"P90TR SE", 
"PSG1", 
"PSG1MOD", 
"PSG1CAMO", 
"PSG1MODCAMO", 
"SPAS12 Gold", 
"SPAS12-Stock Gold", 
"DESERTEAGLE BLACK", 
"DesertEagle gold", 
"M67 Frag Pack", 
"AK-47 D", 
"M4A1 D", 
"MP5A4 D", 
"Knight's SR25 D", 
"L96A1 Black Magnum", 
"AUGA3", 
"aug a1 Black", 
"AUGA3 SE", 
"PP19", 
"pp19mod", 
"PP19 CAMO", 
"PP19MOD CAMO", 
"Double Silver", 
"Double Gold", 
"M1911 Silver", 
"M1911 KNIGHT GOLD", 
"FAMAS D", 
"M24 D", 
"UMP D", 
"Mossberg 590 Military P D", 
"Glock 23 D", 
"HK USP D", 
"SG556", 
"SG550 CAMO", 
"SG556 CAMO", 
"Dragunov SVDS", 
"Dragunov SVDS Ghillie", 
"M32", 
"NULL",//"Claymore", //Trava jogo
"NULL",//"Claymore Controller", 
"Satellite Scanner", 
"Medkit", 
"L85A1", 
"L85A1MOD", 
"L85A1 CAMO", 
"L85A1 MOD CAMO", 
"MK48 CAMO", 
"MK48 MOD", 
"MK48 MOD CAMO", 
"SAIGA20KCQB", 
"SAIGA20K CAMO", 
"SAIGA20K CQB CAMO", 
"USP SE", 
"USP TACTICAL SE", 
"Flamethrower", 
"StaminaKit", 
"NULL",//"Quarantine Host Hand", 
"NULL",//"Quarantine Virus Hand", 
"AK-47 Gold LE", 
"PSG1MOD LE", 
"P90TR LE", 
"Colt Anaconda Silver LE", 
"TAR21", 
"TAR21 CAMO", 
"MTAR21", 
"MTAR21 CAMO", 
"R870SE", 
"R870MCS", 
"R870MCS MOD", 
"MP7", 
"MP7Steel", 
"MP7MOD", 
"MP7MOD Steel", 
"M92FS Silver", 
"M92FS Gold", 
"Mini-Gun Special", 
"SG556 LE", 
"G36E Valkyrie LE", 
"M416CQB LE", 
"PP19 MOD LE", 
"L96A1 ArcticWolf LE", 
"AK74U GoldPlated", 
"AK74M", 
"AK74M GoldPlated", 
"M24A3", 
"M24A3 Woodland", 
"RPK", 
"RPK-74", 
"RPKs MOD", 
"RPK-74M", 
"RPG-7", 
"LGB", 
"G36KE LE", 
"aug a1 Black LE", 
"M4A1 CQBR LE", 
"AK-103 LE", 
"SG550 CAMO LE", 
"MP5RAS LE", 
"PP19 CAMO LE", 
"P90 SE LE", 
"PSG1CAMO LE", 
"Dragunov SVDS LE", 
"MK48 CAMO LE", 
"HalloweenSickle", 
"M14SE", 
"M14CAMO", 
"M14CLASSIC", 
"M416 CAMO", 
"M416 CQB CAMO", 
"FAMAS G2", 
"Scorpion", 
"Scorpion MOD", 
"Scorpion Black", 
"Scorpion Black MOD", 
"G23 CarbonBlack", 
"G23 Chrome", 
"M32 IncendiaryBomb", 
"SCAR-L Trispear LE", 
"Dragunov Black LE", 
"AUGA3 LE", 
"L85A1MOD LE", 
"M417", 
"M417 Combat", 
"M107CQ", 
"M107CQ SE", 
"M107CQ Airforce", 
"M107CQ SE Ghillie", 
"UMP45", 
"M60E4", 
"M60E4 Steel", 
"Airstrike Napalm", 
"Napalm Shell", 
"MP5 SD LE", 
"MTAR21 LE", 
"M4A1 Desert Aim LE", 
"MP7MOD LE", 
"ThanksGiving Melee", 
"M6A2", 
"M6A2 SRT", 
"FAMAS SE", 
"FAMAS G2 SE", 
"L115A2", 
"L115A3", 
"K5SD", 
"K5 CAMO", 
"K5SD CAMO", 
"FirstAidKit", 
"AK74M LE", 
"FAMAS G2 LE", 
"NULL", //"VH Normal NPC", 
"Infected Explode", 
"Infected Gas", 
"NULL", //"VH Explode NPC", 
"NULL", //"VH Heavy NPC", 
"NULL", //"VH Light NPC", 
"L96A1 Black Magnum FT", 
"M32 FT", 
"Mini-Gun Bounty FT", 
"Double Gold FT", 
"Airstrike Napalm FT", 
"Napalm Shell FT", 
"M3 Super 90", 
"NULL", //"M67 FT", 
"REC7", 
"M39EMR", 
"M39EMR Desert", 
"M417 Combat LE", 
"M107CQ SE LE", 
"M6A2 SRT LE", 
"G36E LE", 
"UMP45 LE", 
"M417 SB", 
"M110 SASS", 
"AA-12", 
"Hornet", 
"M16A3 Champion", 
"M16A3 Elite", 
"M16A3 Veteran", 
"M16A3 Professional", 
"ACR LE", 
"AN-94", 
"MG36", 
"M92FS Champion", 
"M92FS Elite", 
"M92FS Veteran", 
"M92FS Professional", 
"M9 Champion", 
"M9 Elite", 
"M9 Veteran", 
"M9 Professional", 
"UMP LE", 
"ACR", 
"ACR Sandfire", 
"CX4 Storm", 
"M960", 
"Mei MP7 MOD", 
"Auto-Turret", 
"NULL",//"Turret-TopGun", 
"REC7 Rangers", 
"G3", 
"M200", 
"M200 Ghillie", 
"SPR", 
"Kriss", 
"Kriss SpecOps", 
"TMP", 
"M21E", 
"DSR-1 Tactical", 
"M32 Stun", 
"Desert American Eagle", 
"Mutation VHand",//"Mutation Quarantine Virus Hand", 
"Guillotine", 
"BaronM416CQB", 
"DSR-1", 
"DSR-1 Subsonic", 
"Ultimax100", 
"IMI Negev", 
"FS2000", 
"F2000", 
"F2000 Tactical", 
"Tracker Knife", 
"TPG-1", 
"TPG-1 Pro", 
"M14EBR", 
"Survival Machete", 
"MG21E", 
"M1866", 
"DomPedroSword", 
"Pumpkin Grenades", 
"Dynamite", 
"Dynamite HE", 
"Dynamite PVE", 
"NULL",//"Quarantine Stick NPC", 
"Dynamite Pack", 
"XK-8", 
"XK-8 Tactical", 
"G36E Valkyrie Maple", 
"P90TR Viper", 
"LAW Maple", 
"M417 CQB", 
"XM8", 
"L96A1 christmas", 
"PP19 MOD Scorpion", 
"Anaconda Gold", 
"P99 clan", 
"Tiger Strider", 
"Candy Cane", 
"TRG-21", 
"TRG-41", 
"TRG SE", 
"Caltrops", 
"MG21E Steel", 
"MG42", 
"TPG-1 Master", 
"S58 Musket", 
"44remrev", 
"HR1860", 
"M1849", 
"C1851N", 
"E57 Musket", 
"Confederate Double Barrel"/*Shotgun*/, 
"32SW2", 
"Colt Dragoon", 
"C1860N", 
"T-2", 
"WA2000", 
"WA2000 Classic", 
"Box Gun", 
"Guitar Gun", 
"M79", 
"PSG1 MARK2", 
"AA-12 MARK2", 
"TAR-21 Camo MARK2", 
"NULL", //"Toygun", 
"Watergun", 
"Beelzebub", 
"P90TR CBS Promotion", 
"SAIGA20K CQB CAMO MARK2", 
"Scorpion MARK2", 
"SG556 MARK2", 
"MZP 1", 
"Alien Gun", 
"MP5A4 NPC", 
"M4A1 NPC", 
"P90 NPC", 
"M416 NPC", 
"MG21E NPC", 
"Watergun NPC", 
"NULL",//"ZVI Falcon", 
"NULL",//"MSR", 
"NULL",//"PSG1 MOD MARK2", 
"MG42 steel", 
"Scorpion Black MOD MARK2", 
"NULL",//"MP5A4 MARK2", 
"NULL",//"Galil ACE 21", 
"NULL",//"Luger P 08", 
"NULL",//"Walther P38", 
"NULL",//"Jackhammer", 
"NULL",//"TAR 21 MARK2", 
"Scorpion Black MARK2", 
"SAIGA 20K CAMO MARK2", 
"ParaFAL"/*, 
"MG2000 Tactical"*/
};